apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terragrunt-version
  title: Run Terragrunt Version
  description: Run Terragrunt Version
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - description
      properties:
        description:
          title: Description
          type: string
          description: Description of the component
          
  steps:
    - id: terragrunt version
      name: run terragrunt version
      action: run:script
      input:
        script: | 
          terragrunt version

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"
